#!/bin/sh
GIT_FOLDER_LOCATION=$(git rev-parse --show-toplevel)
SCRIPT_DIR=$(dirname "${BASH_SOURCE}")
BRANCH_NAME=$1
BRANCH_LABEL=$(cat $GIT_FOLDER_LOCATION/.git/branch_names/$BRANCH_NAME 2>/dev/null)
if [[ $BRANCH_NAME =~ ^BL || $BRANCH_NAME =~ ^OTHERBL ]]; then
	if [[ $BRANCH_LABEL ]]; then
		echo 'Label already exists for '$BRANCH_NAME
	else
		echo '++ Fetching JIRA title for '$BRANCH_NAME'...'
	    python $SCRIPT_DIR/git-fetch.py $BRANCH_NAME > $GIT_FOLDER_LOCATION/.git/branch_names/$BRANCH_NAME
	fi
fi

echo 'New Label: '$(cat $GIT_FOLDER_LOCATION/.git/branch_names/$BRANCH_NAME 2>/dev/null)